name: hello-world
on: push
jobs:
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: mkdir memek  
  job-public-repo-ubuntu2:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: pwd

      
 
